export const SOCIAL = [
    {
        id:'youtube',
        url: 'https://www.youtube.com/c/CiroGomesOficial?sub_confirmation=1',
        src: '/icons/youtube.svg',
        target: '_blank',
        rel: 'noopener noreferrer',
    },
    {
        id:'instagram',
        url: 'https://www.instagram.com/cirogomesoficial/',
        src: '/icons/instagram.svg',
        target: '_blank',
        rel: 'noopener noreferrer',
    },
    {
        id:'facebook',
        url: 'https://www.facebook.com/cirogomesoficial/',
        src: '/icons/facebook.svg',
        target: '_blank',
        rel: 'noopener noreferrer',
    },
    {
        id:'twitter',
        url: 'https://twitter.com/cirogomesoficial',
        src: '/icons/twitter.svg',
        target: '_blank',
        rel: 'noopener noreferrer',
    },
    {
        id:'tiktok',
        url: 'https://www.tiktok.com/@cirogomesoficial',
        src: '/icons/tiktok.svg',
        target: '_blank',
        rel: 'noopener noreferrer',
    },
    {
        id:'whatsapp',
        url: 'https://api.whatsapp.com/send?text=',
        text: 'https://cirogomes.com.br/#rebeldia',
        src: '/icons/whatsapp.svg',
        target: '_blank',
        rel: 'noopener noreferrer',
    },
    {
        id:'linkedin',
        url: 'https://www.linkedin.com/company/ciro-gomes-oficial/',
        src: '/icons/linkedin.svg',
        target: '_blank',
        rel: 'noopener noreferrer',
    },
    {
        id:'telegram',
        url: 'https://t.me/cirogomesoficial',
        src: '/icons/telegram.svg',
        target: '_blank',
        rel: 'noopener noreferrer',
    },
    {
        id:'waze',
        url: 'https://waze.com/ul?acvp=83E482C2-5698-4053-8DC3-87F874FCC6BA',
        src: '/icons/waze.svg',
        target: '_blank',
        rel: 'noopener noreferrer',
    }    
]
